apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gql-todo-k8s
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: gql-todo
  template:
    metadata:
      labels: 
        app: gql-todo
    spec:
      containers: 
      - name: gql-todo-app
        image: gcr.io/gqltodo/gqltodo:v1.2
        ports: 
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: mongodb_uri
        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef:
              name: gql-todo-secret
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gql-todo-k8s-service
spec:
  selector:
    app: gql-todo
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 3000



